#!/bin/sh
# Build tincan, sign it and install it.
#
#   ./scripts/install.sh                 # release build into ~/.local/bin
#   ./scripts/install.sh --debug         # faster build for development
#   PREFIX=/usr/local ./scripts/install.sh
#   TINCAN_SIGNING_IDENTITY="Developer ID Application" ./scripts/install.sh
#
# It also installs a man page to $PREFIX/share/man/man1 and zsh, bash and fish completions,
# generated by the installed tincan, and prints how to enable each.
#
# tincan is signed ad-hoc, which is all a local build needs: macOS gives tincan the privacy
# permissions of the app that runs it; see docs/permissions.md. TINCAN_SIGNING_IDENTITY
# names a certificate in your keychain to sign with instead, by its name, the start of it,
# or its SHA-1. A launchd job that runs tincan directly holds tincan's own permissions,
# which a certificate keeps across rebuilds.
#
# Every build is signed with the hardened runtime, so DYLD_ variables can't load code into
# tincan, and with the Apple Events entitlement that sending needs under it.
set -eu

cd "$(dirname "$0")/.."
. scripts/lib.sh

configuration=release
dry_run=no
for argument in "$@"; do
  case "$argument" in
    --debug) configuration=debug ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "install.sh: unknown option $argument" >&2; exit 2 ;;
  esac
done

prefix="${PREFIX:-$HOME/.local}"
signing_identity="${TINCAN_SIGNING_IDENTITY:--}"

relink_if_embedded_changed "$(swift build -c "$configuration" --show-bin-path)/tincan"
swift build -c "$configuration" --product tincan
binary="$(swift build -c "$configuration" --show-bin-path)/tincan"

if [ "$signing_identity" != "-" ]; then
  identity_line="$(security find-identity -v -p codesigning 2>/dev/null | grep -F -- "$signing_identity" | head -n 1 || true)"
  if [ -z "$identity_line" ]; then
    echo "install.sh: no code-signing certificate in your keychain matches TINCAN_SIGNING_IDENTITY=$signing_identity." >&2
    exit 1
  fi
  # Apple's timestamp server only counts for Developer ID signatures.
  timestamp="--timestamp=none"
  case "$identity_line" in *'"Developer ID Application'*) timestamp="--timestamp" ;; esac
  sign_tincan "$binary" "$signing_identity" "$timestamp"
  echo "Signed with $(printf '%s\n' "$identity_line" | sed -E 's/^[^"]*"([^"]*)".*/\1/')."
else
  sign_tincan "$binary" -
  echo "Signed ad-hoc."
fi

# Never install a build that could load code named by DYLD_ variables.
if ! has_hardened_runtime "$binary"; then
  echo "install.sh: $binary is not signed with the hardened runtime; not installing it." >&2
  exit 1
fi

mkdir -p "$prefix/bin"
# Replace atomically so a running tincan is never left with a half-written binary.
cp "$binary" "$prefix/bin/.tincan.new"
mv -f "$prefix/bin/.tincan.new" "$prefix/bin/tincan"

echo "Installed tincan $("$prefix/bin/tincan" --version) to $prefix/bin/tincan"
on_path=no
case ":$PATH:" in
  *":$prefix/bin:"*) on_path=yes ;;
  *) echo "Add $prefix/bin to your PATH to run tincan from any directory." ;;
esac

# The man page and shell completions, generated by the tincan just installed. The fish
# completion goes to fish's own directory unless PREFIX is set.
man_page="$prefix/share/man/man1/tincan.1"
zsh_completion="$prefix/share/zsh/site-functions/_tincan"
bash_completion="$prefix/share/bash-completion/completions/tincan"
if [ -n "${PREFIX:-}" ]; then
  fish_completion="$prefix/share/fish/vendor_completions.d/tincan.fish"
else
  fish_completion="${XDG_CONFIG_HOME:-$HOME/.config}/fish/completions/tincan.fish"
fi

install_file() {
  mkdir -p "$(dirname "$2")"
  cp "$1" "$2.new"
  chmod 644 "$2.new"
  mv -f "$2.new" "$2"
}

# A path as it would appear in a shell profile, with $HOME for the home directory.
# shellcheck disable=SC2016 # $HOME is meant literally.
profile_path() {
  case "$1" in
    "$HOME"/*) printf '"$HOME%s"' "${1#"$HOME"}" ;;
    *) printf '"%s"' "$1" ;;
  esac
}

extras="$(mktemp -d "${TMPDIR:-/tmp}/tincan-install.XXXXXX")"
trap 'rm -rf "$extras"' EXIT
if generate_extras "$prefix/bin/tincan" "$extras" "$configuration"; then
  install_file "$extras/share/man/man1/tincan.1" "$man_page"
  install_file "$extras/share/zsh/site-functions/_tincan" "$zsh_completion"
  install_file "$extras/share/bash-completion/completions/tincan" "$bash_completion"
  install_file "$extras/share/fish/vendor_completions.d/tincan.fish" "$fish_completion"

  if [ "$(man -w tincan 2>/dev/null)" = "$man_page" ]; then
    man_hint="run \`man tincan\`"
  elif [ "$on_path" = no ]; then
    man_hint="\`man tincan\` finds it once $prefix/bin is on your PATH"
  else
    man_hint="add \`export MANPATH=$(profile_path "$prefix/share/man"):\$MANPATH\` to your shell profile"
  fi
  if [ -n "${PREFIX:-}" ]; then
    fish_hint="fish loads it when $prefix/share is in XDG_DATA_DIRS"
  else
    fish_hint="fish loads it automatically"
  fi
  echo "Man page: $(display_path "$man_page"); $man_hint."
  echo "Zsh completion: $(display_path "$zsh_completion"); add \`fpath=($(profile_path "$(dirname "$zsh_completion")") \$fpath)\` before compinit in ~/.zshrc."
  echo "Bash completion: $(display_path "$bash_completion"); bash-completion 2 loads it, or add \`source $(profile_path "$bash_completion")\` to ~/.bashrc."
  echo "Fish completion: $(display_path "$fish_completion"); $fish_hint."
else
  echo "install.sh: couldn't generate the man page and shell completions; tincan itself is installed." >&2
fi
echo "Next: tincan doctor"
