#!/bin/sh
# Build a release archive: a universal (arm64 and x86_64) tincan signed with a Developer ID
# Application certificate and the hardened runtime, notarized when credentials are set up,
# packaged with its man page and shell completions.
#
#   ./scripts/release.sh             # dist/tincan-<version>-macos.tar.gz and its .sha256
#   ./scripts/release.sh --dry-run   # print the steps instead of running them
#   ./scripts/release.sh --unsigned  # ad-hoc signed test build, never notarized or published
#
#   TINCAN_SIGNING_IDENTITY  Developer ID Application certificate, by name or SHA-1;
#                            default: the first one in the keychain
#   TINCAN_NOTARY_PROFILE    notarytool keychain profile, saved with `xcrun notarytool
#                            store-credentials`; without it the build isn't notarized
#   TINCAN_NOTARY_KEYCHAIN   keychain holding that profile, if not the default one
#
# The version comes from Support/Info.plist, and a signed release needs a clean checkout.
# The archive holds bin/tincan and share/ with the man page, completions, license and
# third-party notices, laid out like an install prefix. Apple can't staple a ticket to a bare binary, so Gatekeeper
# checks the notarization online when a downloaded tincan first runs.
set -eu

cd "$(dirname "$0")/.."
. scripts/lib.sh

dry_run=no
unsigned=no
for argument in "$@"; do
  case "$argument" in
    --dry-run) dry_run=yes ;;
    --unsigned) unsigned=yes ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "release.sh: unknown option $argument" >&2; exit 2 ;;
  esac
done

fail() {
  echo "release.sh: $*" >&2
  exit 1
}

# In a dry run, problems that would stop a release are reported and the steps still shown.
stop() {
  if [ "$dry_run" = yes ]; then
    echo "release.sh: $* A release would stop here." >&2
  else
    fail "$*"
  fi
}

version="$(plutil -extract CFBundleShortVersionString raw -o - Support/Info.plist)"
dist="dist"
stage="$dist/tincan-$version"
archive="tincan-$version-macos.tar.gz"
notary_profile="${TINCAN_NOTARY_PROFILE:-}"
notary_keychain="${TINCAN_NOTARY_KEYCHAIN:-}"

if [ "$unsigned" = yes ]; then
  archive="tincan-$version-macos-unsigned.tar.gz"
  identity=-
else
  identity="${TINCAN_SIGNING_IDENTITY:-$(find_signing_identity "Developer ID Application")}"
  if [ -z "$identity" ]; then
    stop "No Developer ID Application certificate in the keychain. Set TINCAN_SIGNING_IDENTITY, or use --unsigned for a local test build."
    identity="<Developer ID Application>"
  fi
  if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    stop "The checkout has uncommitted changes; release from a clean commit."
  fi
fi

echo "Building $archive" >&2

# 1. A universal release build.
relink_if_embedded_changed "$(swift build -c release --arch arm64 --arch x86_64 --show-bin-path)/tincan"
run swift build -c release --arch arm64 --arch x86_64 --product tincan
binary="$(swift build -c release --arch arm64 --arch x86_64 --show-bin-path)/tincan"

# 2. Stage a copy, so the build output keeps its own signature.
run rm -rf "$stage"
run mkdir -p "$stage/bin"
run cp "$binary" "$stage/bin/tincan"

# 3. Sign the way install.sh does, with a secure timestamp, which notarization requires.
if [ "$unsigned" = yes ]; then
  sign_tincan "$stage/bin/tincan" -
else
  sign_tincan "$stage/bin/tincan" "$identity" --timestamp
fi

# 4. Check the result.
if [ "$dry_run" = no ]; then
  lipo "$stage/bin/tincan" -verify_arch arm64 x86_64 || fail "$stage/bin/tincan is not universal (arm64 and x86_64)."
  codesign --verify --strict "$stage/bin/tincan" || fail "$stage/bin/tincan has an invalid signature."
  has_hardened_runtime "$stage/bin/tincan" || fail "$stage/bin/tincan is not signed with the hardened runtime."
  codesign --display --entitlements - "$stage/bin/tincan" 2>/dev/null | grep -q 'com.apple.security.automation.apple-events' ||
    fail "$stage/bin/tincan is missing the Apple Events entitlement that sending needs."
  if [ "$unsigned" = no ]; then
    details="$(codesign --display --verbose=2 "$stage/bin/tincan" 2>&1)"
    printf '%s\n' "$details" | grep -q '^Authority=Developer ID Application:' ||
      fail "$stage/bin/tincan isn't signed with a Developer ID Application certificate, which notarization needs."
    printf '%s\n' "$details" | grep -q '^Timestamp=' || fail "$stage/bin/tincan has no secure timestamp."
  fi
fi

# 5. Man page and completions, generated by the staged binary.
generate_extras "$stage/bin/tincan" "$stage" release || fail "couldn't generate the man page and completions."
run mkdir -p "$stage/share/doc/tincan"
run cp LICENSE THIRD_PARTY_NOTICES.md "$stage/share/doc/tincan/"

# 6. Notarize. notarytool takes a zip, and the ticket stays with Apple.
if [ "$unsigned" = yes ]; then
  echo "Not notarizing: --unsigned builds are for local testing only." >&2
elif [ -z "$notary_profile" ]; then
  echo "Not notarizing: set TINCAN_NOTARY_PROFILE to a notarytool keychain profile." >&2
else
  if [ "$dry_run" = yes ]; then
    work="<temporary directory>"
  else
    work="$(mktemp -d "${TMPDIR:-/tmp}/tincan-release.XXXXXX")"
    trap 'rm -rf "$work"' EXIT
  fi
  run ditto -c -k --keepParent "$stage/bin/tincan" "$work/tincan.zip"
  run_to "$work/notary.json" xcrun notarytool submit "$work/tincan.zip" --keychain-profile "$notary_profile" \
    ${notary_keychain:+--keychain "$notary_keychain"} --wait --timeout 1h --output-format json || :
  if [ "$dry_run" = no ]; then
    status="$(plutil -extract status raw -o - "$work/notary.json" 2>/dev/null || echo unknown)"
    if [ "$status" != Accepted ]; then
      submission="$(plutil -extract id raw -o - "$work/notary.json" 2>/dev/null || true)"
      if [ -n "$submission" ]; then
        xcrun notarytool log "$submission" --keychain-profile "$notary_profile" \
          ${notary_keychain:+--keychain "$notary_keychain"} >&2 || :
      fi
      fail "notarization finished with status $status."
    fi
    echo "Notarized." >&2
  fi
fi

# 7. Package. COPYFILE_DISABLE keeps macOS metadata files out of the archive.
run rm -f "$dist/$archive" "$dist/$archive.sha256"
run env COPYFILE_DISABLE=1 tar -czf "$dist/$archive" --uid 0 --gid 0 --uname root --gname root \
  -C "$dist" "tincan-$version"
if [ "$dry_run" = yes ]; then
  run shasum -a 256 "$dist/$archive"
  printf '  > %s\n' "$dist/$archive.sha256"
  exit 0
fi
sha256="$(shasum -a 256 "$dist/$archive" | cut -d ' ' -f 1)"
printf '%s  %s\n' "$sha256" "$archive" > "$dist/$archive.sha256"

tar -tzf "$dist/$archive" | sed 's/^/  /'
echo "Archive: $dist/$archive"
echo "SHA-256: $sha256"
if [ "$unsigned" = yes ]; then
  echo "This build is ad-hoc signed and not notarized. Use it only for testing; never publish it." >&2
fi
